// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CoinTraderML.Model
{
    public class ModelInput
    {
        [ColumnName("market"), LoadColumn(0)]
        public string Market { get; set; }


        [ColumnName("candle_date_time_utc"), LoadColumn(1)]
        public string Candle_date_time_utc { get; set; }


        [ColumnName("candle_date_time_kst"), LoadColumn(2)]
        public string Candle_date_time_kst { get; set; }


        [ColumnName("opening_price"), LoadColumn(3)]
        public float Opening_price { get; set; }


        [ColumnName("high_price"), LoadColumn(4)]
        public float High_price { get; set; }


        [ColumnName("low_price"), LoadColumn(5)]
        public float Low_price { get; set; }


        [ColumnName("trade_price"), LoadColumn(6)]
        public float Trade_price { get; set; }


        [ColumnName("timestamp"), LoadColumn(7)]
        public float Timestamp { get; set; }


        [ColumnName("candle_acc_trade_price"), LoadColumn(8)]
        public float Candle_acc_trade_price { get; set; }


        [ColumnName("candle_acc_trade_volume"), LoadColumn(9)]
        public float Candle_acc_trade_volume { get; set; }


        [ColumnName("prev_closing_price"), LoadColumn(10)]
        public float Prev_closing_price { get; set; }


        [ColumnName("change_price"), LoadColumn(11)]
        public float Change_price { get; set; }


        [ColumnName("change_rate"), LoadColumn(12)]
        public float Change_rate { get; set; }


        [ColumnName("converted_trade_price"), LoadColumn(13)]
        public float Converted_trade_price { get; set; }


    }
}
